### ISSUE TITLE
It would be great if it is possible to set delay between page load and screen capture

### ISSUE THREAD

**Issue by jarben** [Szpadel/chrome-headless-render-pdf#21]
Some sites have animations that need to be loaded, if would be great if there is an option where we can set number of milliseconds to wait until the screenshot is taken, for example: waitTime:2000 would wait 2s before taking a screenshot.

**Comment by Szpadel** [comment]
this would extend rendering time,
maybe setting animation playback rate to something like 1000x could solve this issue?

**Comment by jarben** [comment]
The animation playback can't be controlled if this is a third party website. Is the rendering time issue when this is requested in the option? Default would be 0..

**Comment by Szpadel** [comment]
I can alter playback ratio for all animations on rendered page. 1 is normal speed, 0 would cause all animation to stop.
Setting it to 1000 would mean that all animations would be 1000x faster, so everything should finish animating in emulated 5s, but of course I would need to test it somewhere.
Do you have any page on with I could test this issue?

**Comment by jarben** [comment]
That would be great, here is a test link: https://goo.gl/DPfPM4

Output: 
![image](https://user-images.githubusercontent.com/561365/33715394-99747ff6-db52-11e7-8fd6-6c04fc592b86.png)

Desired output: 
![image](https://user-images.githubusercontent.com/561365/33715399-a3d4cb22-db52-11e7-9235-8e7697becc8b.png)

**Comment by jarben** [comment]
Thanks @Szpadel !
