### ISSUE TITLE
Hangs when running on Ubuntu with Chrome 64

### ISSUE THREAD

**Issue by ijdickinson** [Szpadel/chrome-headless-render-pdf#22]
I don't seem to be able to get `chrome-headless-render-pdf` to do anything other than hang. This is what I get for a variety of normal and localhost (my actual use case) web sites:

    $ npx chrome-headless-render-pdf --url 'https://news.bbc.co.uk' --pdf ./output.pdf --chrome-binary=/usr/bin/chromium-browser
    Using /usr/bin/chromium-browser
    Waiting for chrome to became available
    Connected!
    Opening https://news.bbc.co.uk
    ^C

I let it set there for a couple of minutes before killing it. Is there anything I can do to get more diagnostics, to see what's going on?

System info:

- Ubuntu 17.10
- Chromium 64.0.3282.140 (Official Build) Built on Ubuntu , running on Ubuntu 17.10 (64-bit)
- `node -v`  # =>  v8.9.4
- `grep pdf package.json` # =>  "chrome-headless-render-pdf": "^1.5.0",

**Comment by Szpadel** [comment]
Thanks for reporting, I was able to reproduce this issue.
i'll try to find root cause of that.

**Comment by Szpadel** [comment]
Hello, this seams to be chrome issue: https://bugs.chromium.org/p/chromium/issues/detail?id=768961
It is present only with chrome/chromium 64
Please upgrading to 65 seams to solve this issue

**Comment by ijdickinson** [comment]
OK, thanks, will do
