### ISSUE TITLE
GenerateSinglePdf function not working in docker

### ISSUE THREAD

**Issue by AshwinJd** [Szpadel/chrome-headless-render-pdf#38]
The generateSinglePdf function is not working inside the docker container. Does it have something to do with the chrome binary path.?

**Comment by Szpadel** [comment]
This is probably issue with chrome issues when running as root without `--no-sandbox`,
Try running with `{chromeOptions: ['--no-sandbox']}`

**Comment by AshwinJd** [comment]
That solved the issue, but now how will I handle redirections, I have an image to be loaded on to the html which has multiple redirections, but now the image doesnt load up inside the pdf. How can I handle multiple redirections now?

**Comment by Szpadel** [comment]
If it is able to load inside webpage it should also be visible in pdf, try  printing to pdf from normal chrome instance to debug issue

**Comment by khanhhua** [comment]
Should close this issue.

**Comment by AshwinJd** [comment]
Thanks
