### ISSUE TITLE
generating multi-page pdf not working

### ISSUE THREAD

**Issue by dym-sh** [Szpadel/chrome-headless-render-pdf#39]
generating pdf from multiple URLs, with same `--pdf file_name.pdf` output target will just create one (from last used URL)

**Comment by Szpadel** [comment]
this is working like that by design,
each `url-pdf` pair is doing independent generation.
when you specify multiple pairs to the same file, this file will be overwritten.

**Comment by dym-sh** [comment]
> Render multiple pdf files
> > chrome-headless-render-pdf --url http://google.com --pdf **test.pdf** --url file:///tmp/example.html --pdf **test.pdf**

oh, well this thing from the readme is quite misleading

**Comment by Szpadel** [comment]
I will fix that documentation issue
