### ISSUE TITLE
Add support for "headerTemplate" and "footerTemplate" to be used in Chrome's printToPDF method

### ISSUE THREAD

**Issue by Eitz** [Szpadel/chrome-headless-render-pdf#40]
Reference material is here:

https://chromedevtools.github.io/devtools-protocol/tot/Page#method-printToPDF

**Comment by aurelienbobenrieth** [comment]
Hello,

I've been trying to use your branch as a local package for one of my project. However I am not managing to make it work.

The footer template provided in your example only appear at the bottom of my very last page, and does not contain any number. Only the "/" is showing. 

I have something like this (php) : 

`$bin = 'node ' . base_path() . '/node_modules/chrome-headless-render-pdf-canary/cli/chrome-headless-render-pdf.js --include-background --page-width 210mm --page-height 297mm --no-margins --display-header-footer --footer-template \'<style type="text/css">.footer{font-size:8px;width:100%;text-align:center;color:#000;padding-left:0.65cm;}</style><div class="footer"><span class="pageNumber"></span> / <span class="totalPages"></span></div>\' ' .$chrome.' --url file://' . $pathHTML . ' --pdf ' . $pathPDF;`

Do you have an idea of what I am doing wrong ?

**Comment by Eitz** [comment]
Hey @aurelienbobenrieth, sorry, just saw your comment now. Yeah, the CSS for these pages is pretty crazy sometimes. Glad you were able to get it working.
