### ISSUE TITLE
unable to pass options when using programatically

### ISSUE THREAD

**Issue by hansparsons** [Szpadel/chrome-headless-render-pdf#44]
Hi,

how can we pass the options arguments when using the tool programmatically? i'm thinking something like this:

const RenderPDF = require('chrome-headless-render-pdf');
const options = {include-background: true, no-margins: true, page-ranges: '1'};
RenderPDF.generateSinglePdf( 'http://www.google.com', 'output.pdf', options);

**Comment by Szpadel** [comment]
You can check API in https://github.com/Szpadel/chrome-headless-render-pdf/blob/master/index.d.ts
