### ISSUE TITLE
Adding include-background options

### ISSUE THREAD

**Issue by ellier7** [Szpadel/chrome-headless-render-pdf#46]
I am not sure how to add the options to include background when using this code:

ex:
const RenderPDF = require('chrome-headless-render-pdf');

RenderPDF.generatePdfBuffer('http://google.com')
    .then((pdfBuffer) => {
      console.log(pdfBuffer);
    });

**Comment by Prinzhorn** [comment]
https://github.com/Szpadel/chrome-headless-render-pdf/blob/e18df40d5e20acdea279ad2bfcdabad018f60edf/index.js#L60

Does that work?

```js
RenderPDF.generatePdfBuffer('http://google.com', {includeBackground: true})
.then((pdfBuffer) => {
console.log(pdfBuffer);
});
```
