### ISSUE TITLE
AWS Lambda

### ISSUE THREAD

**Issue by Prinzhorn** [Szpadel/chrome-headless-render-pdf#47]
This is just for people like me who are trying to get this to work on Lambda. Now there's a search result, yay.

I'm using the binary from https://github.com/adieuadieu/serverless-chrome/releases

I had to add a few flags to make it run:

```json
{
  chromeBinary: 'bin/headless-chromium-you-have-downloaded',
  chromeOptions: ['--disable-dev-shm-usage', '--no-zygote', '--single-process', '--no-sandbox']
}
```

Source: https://github.com/adieuadieu/serverless-chrome/blob/886c2c4f5c5b2e8f9b79670e0935ee8afb970aab/packages/lambda/src/flags.js

**Comment by sb39** [comment]
@Prinzhorn  can you include the steps ? I am using https://github.com/shelfio/chrome-aws-lambda-layer but have no idea actually how to use it on the runtime

**Comment by Prinzhorn** [comment]
> I am using https://github.com/shelfio/chrome-aws-lambda-layer

I'm not using layers, I literally just have the binary in my project and point `chromeBinary` to it

**Comment by sb39** [comment]
Do you have any sample snippet which I can refer.

**Comment by Prinzhorn** [comment]
Literally https://github.com/alixaxel/chrome-aws-lambda#usage

**Comment by Prinzhorn** [comment]
It's puppeteer-core
