### ISSUE TITLE
--chromeBinary vs. --chrome-binary

### ISSUE THREAD

**Issue by mhienle** [Szpadel/chrome-headless-render-pdf#65]
In https://github.com/Szpadel/chrome-headless-render-pdf/blob/bbf6ef9ca5a2a40ba59f4391dda57f51e2b44047/index.js#L319 the user is asked to provide the option `--chrome-binary`. However, that still fails for me. Only by checking the source code I was able to correctly use the CLI, namely by passing the option `--chromeBinary`.

I'd expect either the message to be correct or the function `detectChrome` to be able to handle both `--chromeBinary` and `--chrome-binary`.

**Comment by Szpadel** [comment]
I believe this is already resolved
