### ISSUE TITLE
Use an existing instance of Chromium

### ISSUE THREAD

**Issue by CrownirBZH** [Szpadel/chrome-headless-render-pdf#84]
Hi!

I'm using your CLI tool on Docker, running on my Mac M2 machine. I use Debian in the container.

I try to create a shell script that launch Chromium once at the startup of the container, and then connect your tool to this existing instance, but I get this error :

<img width="1136" alt="Capture d’écran 2023-02-15 à 22 01 26" src="https://user-images.githubusercontent.com/72704316/219159148-ab040524-4640-417c-a22f-bfd027c53d34.png">

Can you please help?

Thanks!

**Comment by paulwwisl** [comment]
Ask questions on https://stackoverflow.com/ 
then give link here

**Comment by Szpadel** [comment]
This should be already fixed in newest version, please reopen if issues still persists
